### ISSUE TITLE
Align repository name with the package name

### ISSUE THREAD

**Issue by sagikazarmark** [tus/tusd-etcd3-locker#1]
The current repository name is `tusd-etcd3-locker` while the package name is `etcd3locker`. In Go it's considered idiomatic to have the same name as the last segment of the import path as the package name.

Given tus has it's own GH organization, `etcd3locker` sounds like a perfect repository name.

A common alternative is creating a `etcd3locker` package inside the repo to achieve the same result, but that's somewhat redundant.

Also, I would suggest you to consider using vanity import paths. (I know it's a controversial topic, so I won't try to convince you if you disagree. :) )

**Comment by Acconut** [comment]
> A common alternative is creating a etcd3locker package inside the repo to achieve the same result, but that's somewhat redundant.

I like this approach! It allows us to keep the tusd part in the repository name, so people see that this is only usable with tusd. And I am not too concerned about the redundancy in the package path :) Not sure if @chen-anders has an opinion on this?

> Also, I would suggest you to consider using vanity import paths. (I know it's a controversial topic, so I won't try to convince you if you disagree. :) )

Are you talking about something like `tus.io/tusd-etcd3-locker`? While it looks cool, I don't think the benefits are worth the more complex setup we would have to do.

**Comment by sagikazarmark** [comment]
@Acconut well, the "more complex" setup is a JSON file and a list of redirects in an ideal scenario.

I wrote a post about it a while ago: http://sagikazarmark.hu/blog/vanity-import-paths-in-go/

Here is a real life example: https://github.com/logur/vanity-imports

I know I promised I won't try to convince you 😄 , but vanity imports are often misunderstood and that's why people avoid them.

**Comment by Acconut** [comment]
> well, the "more complex" setup is a JSON file and a list of redirects in an ideal scenario.

I am not necessarily talking about how long it would take to set up but rather that it adds another thing to keep in mind when, for example, debugging issues why users cannot import tusd. The mental cost is one of the points I am more concerned about when adding features. The benefits of vanity imports cannot be denied but I don't believe we would gain a lot in value from it. :)

**Comment by chen-anders** [comment]
My apologies for being MIA. 

> A common alternative is creating a etcd3locker package inside the repo to achieve the same result, but that's somewhat redundant.

This is sounds like a good idea to me!
